/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udesc.dsd.dsd65_t1_client.Views.Users;

import javax.swing.JOptionPane;
import udesc.dsd.dsd65_t1_client.Commons.Constants;
import udesc.dsd.dsd65_t1_client.Controllers.UserController;
import udesc.dsd.dsd65_t1_client.Observer.Observer;

/**
 *
 * @author ana
 */
public class CreateUser extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form CreateUser
     */
    
    private UserController controller= new UserController();
    public CreateUser() {
        initComponents();
        controller.append(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgType = new javax.swing.ButtonGroup();
        lbNewUser = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbCPF = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        lbAddress = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        lbDepartment = new javax.swing.JLabel();
        tfDepartment_id = new javax.swing.JTextField();
        rbEmployee = new javax.swing.JRadioButton();
        rbManager = new javax.swing.JRadioButton();
        lbType = new javax.swing.JLabel();
        lbSpeciality = new javax.swing.JLabel();
        cbSpeciality = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNewUser.setText("Novo Usuário");

        lbName.setText("Nome:");

        lbCPF.setText("CPF: ");

        lbAddress.setText("Endereço:");

        lbDepartment.setText("Departamento:");

        bgType.add(rbEmployee);
        rbEmployee.setSelected(true);
        rbEmployee.setText("Funcionário");
        rbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmployeeActionPerformed(evt);
            }
        });

        bgType.add(rbManager);
        rbManager.setText("Gerente");
        rbManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbManagerActionPerformed(evt);
            }
        });

        lbType.setText("Tipo: ");

        lbSpeciality.setText("Turno:");

        cbSpeciality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde" }));

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(lbNewUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbType)
                            .addComponent(lbAddress)
                            .addComponent(lbName)
                            .addComponent(lbCPF)
                            .addComponent(lbDepartment)
                            .addComponent(lbSpeciality))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(rbEmployee)
                                .addGap(104, 104, 104)
                                .addComponent(rbManager))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfName)
                                    .addComponent(tfCPF)
                                    .addComponent(tfAddress)
                                    .addComponent(tfDepartment_id)
                                    .addComponent(cbSpeciality, 0, 360, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnSave)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNewUser)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCPF)
                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAddress)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepartment)
                    .addComponent(tfDepartment_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEmployee)
                    .addComponent(rbManager)
                    .addComponent(lbType))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSpeciality)
                    .addComponent(cbSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         String cpf = this.tfCPF.getText();
        String name = this.tfName.getText();
        String address = this.tfAddress.getText();
        String departmentId = this.tfDepartment_id.getText();
        
        boolean isManager =this.rbManager.isSelected();
        
        String type;
        String speciality;
        if(isManager){
          type =  Constants.TYPE_MANAGER;
          speciality = " ";
        }else{
            type =  Constants.TYPE_EMPLOYEE;
            speciality = this.cbSpeciality.getSelectedItem().toString();
            System.out.println(speciality);
        }
          // INSERT METHOD {"class", "method", "departmentId", "cpf", "name", "address", "type", "speciality"}
        String[] messageData = new String[]{Constants.PERSON_REQUEST,Constants.INSERT,  departmentId, cpf, name, address, type, speciality};
        
        controller.create(messageData);
        clean();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void rbEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmployeeActionPerformed
        this.lbSpeciality.setEnabled(true);
        this.cbSpeciality.setEnabled(true);
    }//GEN-LAST:event_rbEmployeeActionPerformed

    private void rbManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbManagerActionPerformed
        this.lbSpeciality.setEnabled(false);
        this.cbSpeciality.setEnabled(false);
    }//GEN-LAST:event_rbManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgType;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbSpeciality;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbDepartment;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNewUser;
    private javax.swing.JLabel lbSpeciality;
    private javax.swing.JLabel lbType;
    private javax.swing.JRadioButton rbEmployee;
    private javax.swing.JRadioButton rbManager;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfDepartment_id;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void clean(){
        this.tfAddress.setText(Constants.EMPTY);
        this.tfCPF.setText(Constants.EMPTY);
        this.tfDepartment_id.setText(Constants.EMPTY);
        this.tfName.setText(Constants.EMPTY);
    }
    
    
    @Override
    public void notifyView(String msg) {
        JOptionPane.showMessageDialog(null, msg, "Notificação", HEIGHT);
    }
}
