/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udesc.dsd.dsd65_t1_client.Views.Users;

import javax.swing.JOptionPane;
import udesc.dsd.dsd65_t1_client.Commons.Constants;
import static udesc.dsd.dsd65_t1_client.Commons.Constants.DELIMITER;
import udesc.dsd.dsd65_t1_client.Controllers.UserController;
import udesc.dsd.dsd65_t1_client.Observer.Observer;

/**
 *
 * @author ana
 */
public class GetByUser extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form GetByUser
     */
    
    private UserController controller = new UserController();
    private String type;
    public GetByUser() {
        controller.append(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCPF = new javax.swing.JTextField();
        btnSeach = new javax.swing.JButton();
        lbCPF = new javax.swing.JLabel();
        lbtitulo = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        tfDepartment = new javax.swing.JTextField();
        tfSpeciality = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbDepartment = new javax.swing.JLabel();
        lbSpeciality = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSeach.setText("Buscar");
        btnSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachActionPerformed(evt);
            }
        });

        lbCPF.setText("CPF:");

        lbtitulo.setText("Dados do usuário");

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Deletar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lbName.setText("Nome:");

        lbAddress.setText("Endereço:");

        lbDepartment.setText("Departemento: ");

        lbSpeciality.setText("Turno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCPF)
                            .addComponent(lbName)
                            .addComponent(lbAddress)
                            .addComponent(lbDepartment)
                            .addComponent(lbSpeciality))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDepartment)
                            .addComponent(tfAddress)
                            .addComponent(tfName)
                            .addComponent(tfCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(tfSpeciality)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(btnDelete)))
                .addGap(18, 18, 18)
                .addComponent(btnSeach)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(182, 333, Short.MAX_VALUE)
                .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtitulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPF)
                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeach))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddress))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDepartment))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSpeciality)
                    .addComponent(tfSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachActionPerformed

        String cpf = this.tfCPF.getText();
         // GET METHOD    {"class", "method", "", "cpf"}
        String[] request =new String[]{Constants.PERSON_REQUEST, Constants.GET, "", cpf};
        controller.getByIDUser(request);
        
        
        
        if(!controller.getPerson().isBlank()){
        String[] atributtePerson = controller.getPerson().split(";");
        this.tfAddress.setText(atributtePerson[2]);
        this.tfName.setText(atributtePerson[1]);
        this.tfDepartment.setText(atributtePerson[5]);
       
        boolean isManager= atributtePerson[4].equals(Constants.TYPE_MANAGER);
        if(isManager){
            this.type= Constants.TYPE_MANAGER;
            this.tfSpeciality.setEnabled(false);
        }else{
            this.tfSpeciality.setEnabled(true);
            this.type= Constants.TYPE_EMPLOYEE;
            this.tfSpeciality.setText(atributtePerson[3]);
        }
        
        }
       
    }//GEN-LAST:event_btnSeachActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // UPDATE METHOD {"class", "method", "", "cpf", "name", "address", "type", "speciality"}
        String department_id = this.tfDepartment.getText();
        String cpf = this.tfCPF.getText();
        String name = this.tfName.getText();
        String address = this.tfAddress.getText();
        String speciality = this.tfSpeciality.getText();
        
        String[] request = {Constants.PERSON_REQUEST, Constants.UPDATE, department_id, cpf, name, address, type, speciality};
        
        controller.update(request);
        clean();
        
        
        
        
      //String[] request = {Constants.PERSON_REQUEST, Constants.UPDATE, "", msg[0], msg[1], msg[2], "type", "speciality"};
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
    // DELETE METHOD {"class", "method", "", "cpf"}
    
    String[] request = {Constants.PERSON_REQUEST, Constants.DELETE, Constants.EMPTY, this.tfCPF.getText()};
    
    controller.delete(request);
    clean();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSeach;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbDepartment;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSpeciality;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfDepartment;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSpeciality;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notifyView(String msg) {
       JOptionPane.showMessageDialog(null, msg, "Notificação", HEIGHT);
    }

    private void clean() {
        this.tfAddress.setText(Constants.EMPTY);
        this.tfCPF.setText(Constants.EMPTY);
        this.tfName.setText(Constants.EMPTY);
        this.tfDepartment.setText(Constants.EMPTY);
        this.tfSpeciality.setText(Constants.EMPTY);
        
    }
}
