/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udesc.dsd.dsd65_t1_client.Views.Departments;

import java.util.List;
import javax.swing.JOptionPane;
import udesc.dsd.dsd65_t1_client.Commons.Constants;
import udesc.dsd.dsd65_t1_client.Controllers.DepartmentController;
import udesc.dsd.dsd65_t1_client.Observer.Observer;

/**
 *
 * @author ana
 */
public class ListDepartment extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form ListDepartment
     */
    private DepartmentController controller= new DepartmentController();
    
    public ListDepartment() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taListDepartement = new javax.swing.JTextArea();
        lbtitulo = new javax.swing.JLabel();
        btnSeach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taListDepartement.setColumns(20);
        taListDepartement.setRows(5);
        jScrollPane1.setViewportView(taListDepartement);

        lbtitulo.setText("Listar Departamentos? ");

        btnSeach.setText("Sim");
        btnSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeach)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtitulo)
                    .addComponent(btnSeach))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachActionPerformed
        clean();
        
          // LIST METHOD   {"class", "method"}
        String[] request = {Constants.DEPARTMENT_REQUEST, Constants.LIST};
        
        controller.listDepartment(request);
        
        List<String> list = controller.getDepartments();
        
        if(!list.isEmpty()){
            for(String s: list){
               this.taListDepartement.append(s+"\n");
            }
        }
    }//GEN-LAST:event_btnSeachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbtitulo;
    private javax.swing.JTextArea taListDepartement;
    // End of variables declaration//GEN-END:variables

    public void clean(){
        this.taListDepartement.setText(" ");
    }
    @Override
    public void notifyView(String msg) {
       JOptionPane.showMessageDialog(null, msg, "Notificação", HEIGHT);
    }
}
