/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udesc.dsd.dsd65_t1_client.Views;

import udesc.dsd.dsd65_t1_client.Views.Departments.CreateDepartment;
import udesc.dsd.dsd65_t1_client.Views.Departments.GetByDepartement;
import udesc.dsd.dsd65_t1_client.Views.Departments.ListDepartment;
import udesc.dsd.dsd65_t1_client.Views.Users.CreateUser;
import udesc.dsd.dsd65_t1_client.Views.Users.GetByUser;
import udesc.dsd.dsd65_t1_client.Views.Users.ListUsers;

/**
 *
 * @author ana
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MBMenu = new javax.swing.JMenuBar();
        mbEmployees = new javax.swing.JMenu();
        miCreateEmployee = new javax.swing.JMenuItem();
        miListEmployee = new javax.swing.JMenuItem();
        miGetEmployee = new javax.swing.JMenuItem();
        mbDepartments = new javax.swing.JMenu();
        miCreateDepartment = new javax.swing.JMenuItem();
        miGetByIDDepartment = new javax.swing.JMenuItem();
        miListDepartments = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbEmployees.setText("Funcionários");

        miCreateEmployee.setText("Novo usuário");
        miCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCreateEmployeeActionPerformed(evt);
            }
        });
        mbEmployees.add(miCreateEmployee);

        miListEmployee.setText("LIstar usuários");
        miListEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListEmployeeActionPerformed(evt);
            }
        });
        mbEmployees.add(miListEmployee);

        miGetEmployee.setText("Consultar usuário");
        miGetEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGetEmployeeActionPerformed(evt);
            }
        });
        mbEmployees.add(miGetEmployee);

        MBMenu.add(mbEmployees);

        mbDepartments.setText("Departmentos");

        miCreateDepartment.setText("Novo Departamento");
        miCreateDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCreateDepartmentActionPerformed(evt);
            }
        });
        mbDepartments.add(miCreateDepartment);

        miGetByIDDepartment.setText("Consultar Departamento");
        miGetByIDDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGetByIDDepartmentActionPerformed(evt);
            }
        });
        mbDepartments.add(miGetByIDDepartment);

        miListDepartments.setText("LIstar Departamentos");
        miListDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListDepartmentsActionPerformed(evt);
            }
        });
        mbDepartments.add(miListDepartments);

        MBMenu.add(mbDepartments);

        setJMenuBar(MBMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miListEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListEmployeeActionPerformed
        new ListUsers().setVisible(true);
    }//GEN-LAST:event_miListEmployeeActionPerformed

    private void miGetEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGetEmployeeActionPerformed
        new GetByUser().setVisible(true);
    }//GEN-LAST:event_miGetEmployeeActionPerformed

    private void miCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreateEmployeeActionPerformed
        new CreateUser().setVisible(true);
    }//GEN-LAST:event_miCreateEmployeeActionPerformed

    private void miCreateDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCreateDepartmentActionPerformed
        new CreateDepartment().setVisible(true);
    }//GEN-LAST:event_miCreateDepartmentActionPerformed

    private void miListDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListDepartmentsActionPerformed
        new ListDepartment().setVisible(true);
    }//GEN-LAST:event_miListDepartmentsActionPerformed

    private void miGetByIDDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGetByIDDepartmentActionPerformed
        new GetByDepartement().setVisible(true);
    }//GEN-LAST:event_miGetByIDDepartmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MBMenu;
    private javax.swing.JMenu mbDepartments;
    private javax.swing.JMenu mbEmployees;
    private javax.swing.JMenuItem miCreateDepartment;
    private javax.swing.JMenuItem miCreateEmployee;
    private javax.swing.JMenuItem miGetByIDDepartment;
    private javax.swing.JMenuItem miGetEmployee;
    private javax.swing.JMenuItem miListDepartments;
    private javax.swing.JMenuItem miListEmployee;
    // End of variables declaration//GEN-END:variables
}
